name: face_lens
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.12.0
  image: ^4.5.3
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/ml_assets/